FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt
COPY . .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. honeypot.proto
EXPOSE 50051

CMD ["python", "-u", "server.py"]