import grpc
import time
from concurrent import futures
import numpy as np

# These are generated by the Docker build step
import honeypot_pb2
import honeypot_pb2_grpc

class BotClassifierService(honeypot_pb2_grpc.BotClassifierServicer):
    def __init__(self):
        # TODO: Uncomment contents below when the model is trained
        # import joblib
        # self.model = joblib.load('bot_classifier_rf.pkl')
        # self.scaler = joblib.load('scaler.pkl')
        print("Classifier Service Initialized.")

    def ClassifyTraffic(self, request, context):
        print(f"Analyzing IP metrics - Rate: {request.request_rate:.2f}, Variance: {request.time_variance:.2f}")

        # 1. Extract features into a 2D NumPy array for Scikit-Learn
        features = np.array([[
            request.request_rate,
            request.time_variance,
            request.invalid_path_ratio,
            request.payload_entropy
        ]])

        # 2. Real ML Prediction (Commented out until model is trained)
        # scaled_features = self.scaler.transform(features)
        # is_bot_prediction = self.model.predict(scaled_features)[0] == 1
        # confidence_score = float(self.model.predict_proba(scaled_features)[0][1])

        # 3. Dummy Heuristic Fallback (Use this to test the Java connection today)
        is_bot = False
        confidence = 0.10

        # Example logic: High request rate with robotic consistency (low variance) is a bot
        if request.request_rate > 5.0 or request.invalid_path_ratio > 0.5:
            is_bot = True
            confidence = 0.95
        elif request.time_variance < 0.1 and request.request_rate > 2.0:
            is_bot = True
            confidence = 0.85

        print(f"Verdict: Bot={is_bot} (Confidence: {confidence:.2f})")

        # 4. Return the Protobuf object back to Spring Boot
        return honeypot_pb2.PredictionResult(
            is_bot=is_bot,
            confidence=confidence
        )

def serve():
    # Setup the gRPC server pool
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

    # Bind our custom service to the gRPC server
    honeypot_pb2_grpc.add_BotClassifierServicer_to_server(BotClassifierService(), server)

    # Listen on all interfaces on port 50051
    server.add_insecure_port('[::]:50051')
    print("Python gRPC Bot Classifier started on port 50051...")

    server.start()
    server.wait_for_termination()

if __name__ == '__main__':
    serve()