name: Security & Detection Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  validate-security-and-crypto:
    runs-on: ubuntu-latest

    steps:
      - name: checkout (source code)
        uses: actions/checkout@v5

      - name: Set up JDK 24 (Project Panama & Vector API)
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: run all testcases
        env:
          MAVEN_OPTS: "--add-modules jdk.incubator.vector"
        run: mvn clean verify -DargLine="--add-modules jdk.incubator.vector"

      - name: verify Docker image-build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: online-encryption-hub:latest